### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
pip install tensorflow

In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[3910, 8430, 1243, 2426], [3910, 8430, 1243, 3886], [3910, 1805, 1243, 1197], [6477, 9846, 5890, 3045, 5495], [6477, 9846, 5890, 3045, 1265], [9191, 3910, 7281, 1243, 4446], [8641, 9494, 198, 3045]]


### Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3910 8430 1243 2426]
 [   0    0    0    0 3910 8430 1243 3886]
 [   0    0    0    0 3910 1805 1243 1197]
 [   0    0    0 6477 9846 5890 3045 5495]
 [   0    0    0 6477 9846 5890 3045 1265]
 [   0    0    0 9191 3910 7281 1243 4446]
 [   0    0    0    0 8641 9494  198 3045]]


In [ ]:
dim=10


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step
[[[-0.04977303  0.02570062 -0.04809116  0.0374717  -0.04717983
   -0.04784042 -0.03125979  0.0066854   0.02975725 -0.02025652]
  [-0.04977303  0.02570062 -0.04809116  0.0374717  -0.04717983
   -0.04784042 -0.03125979  0.0066854   0.02975725 -0.02025652]
  [-0.04977303  0.02570062 -0.04809116  0.0374717  -0.04717983
   -0.04784042 -0.03125979  0.0066854   0.02975725 -0.02025652]
  [-0.04977303  0.02570062 -0.04809116  0.0374717  -0.04717983
   -0.04784042 -0.03125979  0.0066854   0.02975725 -0.02025652]
  [ 0.00517061 -0.02907349  0.00559924 -0.03559706  0.03375055
    0.02961299 -0.00701767  0.04797349  0.01447921  0.00680964]
  [-0.04373155 -0.02683691 -0.02678274 -0.00688631 -0.04496398
    0.04484756 -0.00232857 -0.04058076 -0.03966224 -0.00114751]
  [-0.04160307 -0.03779814 -0.0481489  -0.01611829 -0.03143585
    0.04218036  0.00249999  0.03904508  0.02180203 -0.01771889]
  [-0.03238489  0.0342905  -0.00491576 -0.04465185  0.04095835
   -0.039

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 3910, 8430, 1243, 2426], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[-0.04977303  0.02570062 -0.04809116  0.0374717  -0.04717983 -0.04784042
  -0.03125979  0.0066854   0.02975725 -0.02025652]
 [-0.04977303  0.02570062 -0.04809116  0.0374717  -0.04717983 -0.04784042
  -0.03125979  0.0066854   0.02975725 -0.02025652]
 [-0.04977303  0.02570062 -0.04809116  0.0374717  -0.04717983 -0.04784042
  -0.03125979  0.0066854   0.02975725 -0.02025652]
 [-0.04977303  0.02570062 -0.04809116  0.0374717  -0.04717983 -0.04784042
  -0.03125979  0.0066854   0.02975725 -0.02025652]
 [ 0.00517061 -0.02907349  0.00559924 -0.03559706  0.03375055  0.02961299
  -0.00701767  0.04797349  0.01447921  0.00680964]
 [-0.04373155 -0.02683691 -0.02678274 -0.00688631 -0.04496398  0.04484756
  -0.00232857 -0.04058076 -0.03966224 -0.00114751]
 [-0.04160307 -0.03779814 -0.0481489  -0.01611829 -0.03143585  0.04218036
   0.00249999  0.03904508  0.02180203 -0.01771889]
 [-0.03238489  0.0342905  -0.00491576 -0.04465185  0.04095835 -0.03909769
  -0.02199599